### PR TITLE
Begin adding support for multiple openvpn 'statusfile' parameters

### PR DESCRIPTION
**Pull request by tbielawa**
The collectd openvpn plugin supports multiple `StatusFile` parameters in the plugins configuration file. This patch adds support for that same functionality via the collectd puppet module.

### CODE REVIEW

**Comment by blkperl** [comment]
Can you add a spec test to verify the behavior?

**Comment by tbielawa** [comment]
Ill try my best

**Comment by tbielawa** [comment]
Uhoh. tests passed locally. Checking out why those failed now. Probably an environment delta.

**Comment by tbielawa** [comment]
@blkperl oh yeah! All passing now :-)

**Comment by blkperl** [comment]
Awesome thanks for the contribution!

**Pull request merged**
