### PR TITLE
Fix collectd::plugin::write_http for RedHat

### PR DESCRIPTION
**Pull request by simonpasquier**
This change reverts commit a334b6e and closes issue #251. The main RPM
repositories (eg, Fedora and EPEL) don't ship the collectd-write_http
package (instead the plugin is included in the core collectd package).
In case the collectd-write_http needs to be installed, it can be done
outside of the collectd manifests.

### CODE REVIEW

**Comment by blkperl** [comment]
Rebase your changes to get the fixed tests

**Comment by blkperl** [comment]
Is this going to break Centos5 or Centos6?

**Comment by simonpasquier** [comment]
AFAICT it may break for people that are using custom repositories for installing the collectd packages. Like I said in the initial comment, Fedora and its EPEL derivatives [1] don't ship the write_http plugin as a separate package.

[1] https://apps.fedoraproject.org/packages/collectd/overview/

**Comment by blkperl** [comment]
Thanks for the contribution

**Pull request merged**
