### PR TITLE
Added v5_upgrade Plugin: https://collectd.org/wiki/index.php/Target:v5_u...

### PR DESCRIPTION
**Pull request by michakrause**
...pgrade

### CODE REVIEW

**Comment by blkperl** [comment]
Please add docs to the README.md

**Comment by michakrause** [comment]
I added something to README.md, is this sufficient?

**Comment by txaj** [comment]
:+1:

**Comment by txaj** [comment]
@michakrause and thank you very much for your PR on collectd

**Comment by blkperl** [comment]
Thanks!

**Pull request merged**
